### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by stserakhau** [Auties00/Whatsapp4j#208]
version 3.0.5

Method threw 'java.lang.StackOverflowError' exception. Cannot evaluate it.auties.whatsapp.model.message.button.ButtonsResponseMessage.toString()

**Comment by Auties00** [comment]
> version 3.0.5
> 
> Method threw 'java.lang.StackOverflowError' exception. Cannot evaluate it.auties.whatsapp.model.message.button.ButtonsResponseMessage.toString()

Will be fixed in 3.1
I already fixed it on the main branch but I first need to finish some things before I release it

**Comment by Auties00** [comment]
Released 3.1
