### ISSUE TITLE
Strange behaviour on sending the image message

### ISSUE THREAD

**Issue by stserakhau** [Auties00/Whatsapp4j#216]
Test case
1. WhatsUp mobile + desktop + api linked with the same account
2. When I send DocumentMessage via api it delivered to all devices
3. When I send ImageMessage via api it delivered to desktop only

```
----- delivered to desktop and mobile
DocumentMessage dm = DocumentMessage.simpleBuilder()
                        .media(mediaResult.data)
                        .title(mediaResult.sourceUuid.toString())
                        .fileName(mediaResult.sourceUuid.toString())
                        .thumbnail(mediaResult.data)
                        .build();
bot.sendMessage(chatId, dm);

-----
delivered to desktop app only

ImageMessage message = ImageMessage.builder()
                        .caption(caption)
                        .decodedMedia(mediaResult.data)
                        .width(mediaResult.width)
                        .height(mediaResult.height)
                        .mimetype("image/jpg")
                        .build();

bot.sendMessage(chatId, message);
-----


sendMessage(chatId, message) {
    ContactJid contact = cache.computeIfAbsent(chatId, cid -> {
            for (Contact c1 : whatsapp.store().contacts()) {
                if (chatId.equals(c1.jid().user())) {
                    return c1.jid();
                }
            }
            throw new RuntimeException("Contact not found: " + chatId);
        });

    this.whatsapp.sendMessage(contact, message);
}
```

**Comment by Auties00** [comment]
> Test case
> 1. WhatsUp mobile + desktop + api linked with the same account
> 2. When I send DocumentMessage via api it delivered to all devices
> 3. When I send ImageMessage via api it delivered to desktop only
> 
> ```
> ----- delivered to desktop and mobile
> DocumentMessage dm = DocumentMessage.simpleBuilder()
>                         .media(mediaResult.data)
>                         .title(mediaResult.sourceUuid.toString())
>                         .fileName(mediaResult.sourceUuid.toString())
>                         .thumbnail(mediaResult.data)
>                         .build();
> bot.sendMessage(chatId, dm);
> 
> -----
> delivered to desktop app only
> 
> ImageMessage message = ImageMessage.builder()
>                         .caption(caption)
>                         .decodedMedia(mediaResult.data)
>                         .width(mediaResult.width)
>                         .height(mediaResult.height)
>                         .mimetype("image/jpg")
>                         .build();
> 
> bot.sendMessage(chatId, message);
> -----
> 
> 
> sendMessage(chatId, message) {
>     ContactJid contact = cache.computeIfAbsent(chatId, cid -> {
>             for (Contact c1 : whatsapp.store().contacts()) {
>                 if (chatId.equals(c1.jid().user())) {
>                     return c1.jid();
>                 }
>             }
>             throw new RuntimeException("Contact not found: " + chatId);
>         });
> 
>     this.whatsapp.sendMessage(contact, message);
> }
> ```

Api version?

**Comment by stserakhau** [comment]
3.1.2

**Comment by Auties00** [comment]
> 3.1.2

I'll look into it after school

**Comment by Auties00** [comment]
> Test case
> 1. WhatsUp mobile + desktop + api linked with the same account
> 2. When I send DocumentMessage via api it delivered to all devices
> 3. When I send ImageMessage via api it delivered to desktop only
> 
> ```
> ----- delivered to desktop and mobile
> DocumentMessage dm = DocumentMessage.simpleBuilder()
>                         .media(mediaResult.data)
>                         .title(mediaResult.sourceUuid.toString())
>                         .fileName(mediaResult.sourceUuid.toString())
>                         .thumbnail(mediaResult.data)
>                         .build();
> bot.sendMessage(chatId, dm);
> 
> -----
> delivered to desktop app only
> 
> ImageMessage message = ImageMessage.builder()
>                         .caption(caption)
>                         .decodedMedia(mediaResult.data)
>                         .width(mediaResult.width)
>                         .height(mediaResult.height)
>                         .mimetype("image/jpg")
>                         .build();
> 
> bot.sendMessage(chatId, message);
> -----
> 
> 
> sendMessage(chatId, message) {
>     ContactJid contact = cache.computeIfAbsent(chatId, cid -> {
>             for (Contact c1 : whatsapp.store().contacts()) {
>                 if (chatId.equals(c1.jid().user())) {
>                     return c1.jid();
>                 }
>             }
>             throw new RuntimeException("Contact not found: " + chatId);
>         });
> 
>     this.whatsapp.sendMessage(contact, message);
> }
> ```

Can you try without specifying the mime type explicitly?

**Comment by stserakhau** [comment]
Test case 1:
```
ImageMessage message = ImageMessage.builder()
                        .caption(caption)
                        .decodedMedia(mediaResult.data)
                        .width(mediaResult.width)
                        .height(mediaResult.height)
                        .build();
```
image response rendered on desktop client only

Test case 2 (success):

```
                ImageMessage message = ImageMessage.builder()
                        .caption(caption)
                        .decodedMedia(mediaResult.data)
                        .width(mediaResult.width)
                        .height(mediaResult.height)
                        .mimetype("image/jpeg")
                        .build();
```

image response rendered on both - mobile and desktop

**Comment by Auties00** [comment]
> Test case 1:
> 
> ```
> ImageMessage message = ImageMessage.builder()
>                         .caption(caption)
>                         .decodedMedia(mediaResult.data)
>                         .width(mediaResult.width)
>                         .height(mediaResult.height)
>                         .build();
> ```
> 
> image response rendered on desktop client only
> 
> Test case 2 (success):
> 
> ```
>                 ImageMessage message = ImageMessage.builder()
>                         .caption(caption)
>                         .decodedMedia(mediaResult.data)
>                         .width(mediaResult.width)
>                         .height(mediaResult.height)
>                         .mimetype("image/jpeg")
>                         .build();
> ```
> 
> image response rendered on both - mobile and desktop

You should be using the simpleBuilder, not the builder. That's why
