### ISSUE TITLE
Issue with loading of the classes.

### ISSUE THREAD

**Issue by stserakhau** [Auties00/Whatsapp4j#223]
Use case: spring boot application with plugins which loaded from own class path

```
       SYSTEM_EXECUTOR.execute(() -> {
1.             Thread.currentThread().setContextClassLoader(Whatsapp.class.getClassLoader());
            var whatsapp = Whatsapp.lastConnection(
                    defaultOptions()
                            .qrHandler(QrHandler.toFile(path -> {
                                botQrCodeFile = path.toFile();
                            }))
                            .name("WhatsApp Integration"));
            whatsapp.addListener(this);
            log.info("Starting");
            whatsapp.connect().join();
            log.info("Stopped");
        });



    public final static class WebSocketSession extends SocketSession {
        private Session session;

        @Override
        public CompletableFuture<Void> connect(SocketListener listener) {
2. >>>            .... Thread.currentThread().getContextClassLoader() = class loader from the line 1 .....
            return CompletableFuture.runAsync(() -> {
3. >>>            .... Thread.currentThread().getContextClassLoader() = Application level class loader which doesn't see whatsup classes .....
                try {
4. >>>                    super.connect(listener);
                    ContainerProvider.getWebSocketContainer().connectToServer(this, WEB_ENDPOINT);
                } catch (IOException exception) {
                    throw new UncheckedIOException("Cannot connect to host", exception);
                } catch (DeploymentException exception) {
                    throw new RuntimeException(exception);
                }
            });
        }
........

line 3 is the cause of exception "Could not find an implementation class."

public abstract class ContainerProvider {
    public ContainerProvider() {
    }

    public static WebSocketContainer getWebSocketContainer() {
        Iterator<ContainerProvider> providers = ServiceLoader.load(ContainerProvider.class).iterator();
        if (!providers.hasNext()) {
>>>            throw new RuntimeException("Could not find an implementation class.");
        } else {
            do {
                ContainerProvider impl = (ContainerProvider)providers.next();
                WebSocketContainer wsc = impl.getContainer();
                if (wsc != null) {
                    return wsc;
                }
            } while(providers.hasNext());

            throw new RuntimeException("Could not find an implementation class with a non-null WebSocketContainer.");
        }
    }

    protected abstract WebSocketContainer getContainer();
}
```

To fix issue with classloading I executed line
Thread.currentThread().setContextClassLoader(Whatsapp.class.getClassLoader());
when debugger stopped on line 4

The same issue described here
https://stackoverflow.com/questions/49113207/completablefuture-forkjoinpool-set-class-loader

and how to fix it. General sence - need configuration option to provide custom executor to second parameter of

CompletableFuture.runAsync( ()->{}, ...here... )

**Comment by Auties00** [comment]
Doesn't the pinned issue about this same thing fix your problem?

**Comment by stserakhau** [comment]
It will solve, but I need possibility to inject reference to the factory.

```
it.auties.whatsapp.socket.SocketSession
-> WebSocketSession
        @Override
        public CompletableFuture<Void> connect(SocketListener listener) {
            return CompletableFuture.runAsync(() -> {
                try {
                    super.connect(listener);
                    ContainerProvider.getWebSocketContainer().connectToServer(this, WEB_ENDPOINT);
                } catch (IOException exception) {
                    throw new UncheckedIOException("Cannot connect to host", exception);
                } catch (DeploymentException exception) {
                    throw new RuntimeException(exception);
                }
            }, **>>>> here <<<<<** ); <<<< need to put factory as second argument of this method
        }
```

**Comment by Auties00** [comment]
You can just use CompletableFuture.defaultExecutor() to get an instance of the executor that the library is using. This should fix it

**Comment by stserakhau** [comment]
it's inside of Whatsapp4j

on business level I have next code
```
SYSTEM_EXECUTOR.execute(() -> {
              Thread.currentThread().setContextClassLoader(Whatsapp.class.getClassLoader());
1            var whatsapp = Whatsapp.lastConnection(...);
2.           whatsapp.addListener(this);
3.            whatsapp.connect().join();
});
```

code of line 3 contains execution of CompletableFuture.runAsync, internal pool initialized on application startup. and referenced to application classloader, which is not contains loaded classes of whatsup4j. But core module initialize loading of the submodules by another classloader. Result of this when whatsapp.connect() trying to get ContainerProvider.getWebSocketContainer() it doesn't found Grizzly implementation because CompletableFuture.runAsync uses core classloader.

I see the solution something like this

```
SYSTEM_EXECUTOR.execute(() -> {
            var whatsapp = Whatsapp.lastConnection(
                   defaultOptions()
++++               .threadFactory(factoryReference)
            );
           whatsapp.addListener(this);
           whatsapp.connect().join();
});
```

and modification inside 
```
it.auties.whatsapp.socket.SocketSession
-> WebSocketSession
        @Override
        public CompletableFuture<Void> connect(SocketListener listener) {
            return CompletableFuture.runAsync(() -> {
                try {
                    super.connect(listener);
                    ContainerProvider.getWebSocketContainer().connectToServer(this, WEB_ENDPOINT);
                } catch (IOException exception) {
                    throw new UncheckedIOException("Cannot connect to host", exception);
                } catch (DeploymentException exception) {
                    throw new RuntimeException(exception);
                }
+++       }, factory); <<<< need to put factory as second argument of CompletableFuture.runAsync method
        }
```

**Comment by stserakhau** [comment]
I tried to push fix in separated branch but 403

**WhatsappOptions.java**
```
    @Default
    private TextPreviewSetting textPreviewSetting = TextPreviewSetting.ENABLED_WITH_INFERENCE;

+    /**
+     * Executor service
+     */
+    @Default
+    private ExecutorService executorService = Executors.newSingleThreadScheduledExecutor();//ForkJoinPool.commonPool();

    /**
     * Handles failures in the WebSocket. By default, uses the simple handler and prints to the
     * terminal.
     */
    @Default
    private ErrorHandler errorHandler = ErrorHandler.toTerminal();
```

**SocketSession.java**
```
package it.auties.whatsapp.socket;

import it.auties.whatsapp.api.WhatsappOptions;
import it.auties.whatsapp.socket.SocketSession.AppSocketSession;
import it.auties.whatsapp.socket.SocketSession.WebSocketSession;
import it.auties.whatsapp.socket.SocketSession.WebSocketSession.OriginPatcher;
import it.auties.whatsapp.util.Specification;
import jakarta.websocket.*;
import jakarta.websocket.ClientEndpointConfig.Configurator;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.SocketException;
import java.nio.ByteBuffer;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;

import static it.auties.whatsapp.util.Specification.Whatsapp.*;

@RequiredArgsConstructor
@SuppressWarnings({"unused", "UnusedReturnValue"})
public abstract sealed class SocketSession permits WebSocketSession, AppSocketSession {
    protected final ExecutorService executorService;
    protected UUID uuid;
    protected SocketListener listener;
    protected boolean closed;

    static SocketSession of(WhatsappOptions options) {
        return switch (options.clientType()) {
            case WEB_CLIENT -> new WebSocketSession(options.executorService());
            case APP_CLIENT -> new AppSocketSession(options.executorService());
        };
    }

    public CompletableFuture<Void> connect(SocketListener listener) {
        this.uuid = UUID.randomUUID();
        this.listener = listener;
        this.closed = false;
        return null;
    }

    public CompletableFuture<Void> close() {
        this.closed = true;
        return null;
    }

    abstract boolean isOpen();

    public abstract CompletableFuture<Void> sendBinary(byte[] bytes);

    @ClientEndpoint(configurator = OriginPatcher.class)
    public final static class WebSocketSession extends SocketSession {
        private Session session;

        public WebSocketSession(ExecutorService executor) {
            super(executor);
        }

        @Override
        public CompletableFuture<Void> connect(SocketListener listener) {
            return CompletableFuture.runAsync(() -> {
                try {
                    super.connect(listener);
                    ContainerProvider.getWebSocketContainer().connectToServer(this, WEB_ENDPOINT);
                } catch (IOException exception) {
                    throw new UncheckedIOException("Cannot connect to host", exception);
                } catch (DeploymentException exception) {
                    throw new RuntimeException(exception);
                }
            }, executorService);
        }

        @Override
        public CompletableFuture<Void> close() {
            return CompletableFuture.runAsync(() -> {
                try {
                    if (closed) {
                        return;
                    }

                    session.close();
                    super.close();
                } catch (IOException exception) {
                    throw new UncheckedIOException("Cannot close connection to host", exception);
                }
            }, executorService);
        }

        @Override
        public boolean isOpen() {
            return session == null || session.isOpen();
        }

        @Override
        public CompletableFuture<Void> sendBinary(byte[] bytes) {
            var currentUuid = this.uuid;
            var future = new CompletableFuture<Void>();
            try {
                session.getAsyncRemote().sendBinary(ByteBuffer.wrap(bytes), result -> {
                    if(!Objects.equals(this.uuid, currentUuid)){
                        future.completeExceptionally(new IllegalStateException("Cannot send request: session was closed"));
                        return;
                    }

                    if (result.isOK()) {
                        future.complete(null);
                        return;
                    }

                    future.completeExceptionally(result.getException());
                });
            } catch (Throwable throwable) {
                future.completeExceptionally(throwable);
            }
            return future;
        }

        @OnOpen
        public void onOpen(Session session) {
            this.session = session;
            listener.onOpen(this);
        }

        @OnClose
        public void onClose(Session session, CloseReason closeReason) {
            listener.onClose();
        }

        @OnError
        public void onError(Throwable throwable) {
            listener.onError(throwable);
        }

        @OnMessage
        public void onBinary(byte[] message) {
            listener.onMessage(message);
        }

        public static class OriginPatcher extends Configurator {
            @Override
            public void beforeRequest(@NonNull Map<String, List<String>> headers) {
                headers.put("Origin", List.of(Specification.Whatsapp.WEB_ORIGIN));
                headers.put("Host", List.of(Specification.Whatsapp.WEB_HOST));
            }
        }
    }

    public final static class AppSocketSession extends SocketSession {
        private static final int MAX_READ_SIZE = 65535;

        private Socket socket;

        public AppSocketSession(ExecutorService executor) {
            super(executor);
        }

        @Override
        public CompletableFuture<Void> connect(SocketListener listener) {
            if(socket != null && isOpen()){
                return CompletableFuture.completedFuture(null);
            }

            return CompletableFuture.runAsync(() -> {
                try {
                    super.connect(listener);
                    this.socket = new Socket();
                    socket.setKeepAlive(true);
                    socket.connect(new InetSocketAddress(APP_ENDPOINT_HOST, APP_ENDPOINT_PORT));
                    executorService.execute(this::readMessages);
                    listener.onOpen(this);
                } catch (IOException exception) {
                    throw new UncheckedIOException("Cannot connect to host", exception);
                }
            }, executorService);
        }

        @Override
        public CompletableFuture<Void> close() {
            if(socket == null || !isOpen()){
                return CompletableFuture.completedFuture(null);
            }

            return CompletableFuture.runAsync(() -> {
                try {
                    super.close();
                    socket.close();
                    closeResources();
                } catch (IOException exception) {
                    throw new UncheckedIOException("Cannot close connection to host", exception);
                }
            });
        }

        @Override
        public boolean isOpen() {
            return socket.isConnected();
        }

        @Override
        public CompletableFuture<Void> sendBinary(byte[] bytes) {
            return CompletableFuture.runAsync(() -> {
                try {
                    var stream = socket.getOutputStream();
                    stream.write(bytes);
                    stream.flush();
                } catch (IOException exception) {
                    throw new UncheckedIOException("Cannot send message", exception);
                }
            }, executorService);
        }

        private void readMessages() {
            var bytes = new byte[MAX_READ_SIZE];
            while (isOpen()) {
                try {
                    var stream = socket.getInputStream();
                    var size = stream.read(bytes);
                    listener.onMessage(Arrays.copyOf(bytes, size));
                } catch (SocketException exception) {
                    closeResources();
                } catch (IOException exception) {
                    listener.onError(exception);
                }
            }
            closeResources();
        }

        private void closeResources() {
            this.socket = null;
            executorService.shutdownNow();
            listener.onClose();
        }
    }
}

```

**SocketHandler.java**

```
    public CompletableFuture<Void> connect() {
        if (authFuture == null || authFuture.isDone()) {
            this.authFuture = new CompletableFuture<>();
        }

        if(options instanceof MobileOptions mobileOptions && !keys.registered()){
            authHandler.checkRegistrationStatus();
        }

---    this.session = SocketSession.of(options.clientType());
+++ this.session = SocketSession.of(options);
        return session.connect(this).thenCompose(ignored -> authFuture);
    }
```

**Comment by Auties00** [comment]
> I tried to push fix in separated branch but 403. This update solved my issue
> 
> **WhatsappOptions.java**
> 
> ```
>     @Default
>     private TextPreviewSetting textPreviewSetting = TextPreviewSetting.ENABLED_WITH_INFERENCE;
> 
> +    /**
> +     * Executor service
> +     */
> +    @Default
> +    private ExecutorService executorService = Executors.newSingleThreadScheduledExecutor();//ForkJoinPool.commonPool();
> 
>     /**
>      * Handles failures in the WebSocket. By default, uses the simple handler and prints to the
>      * terminal.
>      */
>     @Default
>     private ErrorHandler errorHandler = ErrorHandler.toTerminal();
> ```
> 
> **SocketSession.java**
> 
> ```
> package it.auties.whatsapp.socket;
> 
> import it.auties.whatsapp.api.WhatsappOptions;
> import it.auties.whatsapp.socket.SocketSession.AppSocketSession;
> import it.auties.whatsapp.socket.SocketSession.WebSocketSession;
> import it.auties.whatsapp.socket.SocketSession.WebSocketSession.OriginPatcher;
> import it.auties.whatsapp.util.Specification;
> import jakarta.websocket.*;
> import jakarta.websocket.ClientEndpointConfig.Configurator;
> import lombok.NonNull;
> import lombok.RequiredArgsConstructor;
> 
> import java.io.IOException;
> import java.io.UncheckedIOException;
> import java.net.InetSocketAddress;
> import java.net.Socket;
> import java.net.SocketException;
> import java.nio.ByteBuffer;
> import java.util.*;
> import java.util.concurrent.CompletableFuture;
> import java.util.concurrent.ExecutorService;
> 
> import static it.auties.whatsapp.util.Specification.Whatsapp.*;
> 
> @RequiredArgsConstructor
> @SuppressWarnings({"unused", "UnusedReturnValue"})
> public abstract sealed class SocketSession permits WebSocketSession, AppSocketSession {
> +    protected final ExecutorService executorService;
>     protected UUID uuid;
>     protected SocketListener listener;
>     protected boolean closed;
> 
> U    static SocketSession of(WhatsappOptions options) {
> U        return switch (options.clientType()) {
> U            case WEB_CLIENT -> new WebSocketSession(options.executorService());
> U            case APP_CLIENT -> new AppSocketSession(options.executorService());
>         };
>     }
> 
>     public CompletableFuture<Void> connect(SocketListener listener) {
>         this.uuid = UUID.randomUUID();
>         this.listener = listener;
>         this.closed = false;
>         return null;
>     }
> 
>     public CompletableFuture<Void> close() {
>         this.closed = true;
>         return null;
>     }
> 
>     abstract boolean isOpen();
> 
>     public abstract CompletableFuture<Void> sendBinary(byte[] bytes);
> 
>     @ClientEndpoint(configurator = OriginPatcher.class)
>     public final static class WebSocketSession extends SocketSession {
>         private Session session;
> 
> +        public WebSocketSession(ExecutorService executor) {
> +            super(executor);
> +        }
> 
>         @Override
>         public CompletableFuture<Void> connect(SocketListener listener) {
>             return CompletableFuture.runAsync(() -> {
>                 try {
>                     super.connect(listener);
>                     ContainerProvider.getWebSocketContainer().connectToServer(this, WEB_ENDPOINT);
>                 } catch (IOException exception) {
>                     throw new UncheckedIOException("Cannot connect to host", exception);
>                 } catch (DeploymentException exception) {
>                     throw new RuntimeException(exception);
>                 }
> U            }, executorService);
>         }
> 
>         @Override
>         public CompletableFuture<Void> close() {
>             return CompletableFuture.runAsync(() -> {
>                 try {
>                     if (closed) {
>                         return;
>                     }
> 
>                     session.close();
>                     super.close();
>                 } catch (IOException exception) {
>                     throw new UncheckedIOException("Cannot close connection to host", exception);
>                 }
> U            }, executorService);
>         }
> 
>         @Override
>         public boolean isOpen() {
>             return session == null || session.isOpen();
>         }
> 
>         @Override
>         public CompletableFuture<Void> sendBinary(byte[] bytes) {
>             var currentUuid = this.uuid;
>             var future = new CompletableFuture<Void>();
>             try {
>                 session.getAsyncRemote().sendBinary(ByteBuffer.wrap(bytes), result -> {
>                     if(!Objects.equals(this.uuid, currentUuid)){
>                         future.completeExceptionally(new IllegalStateException("Cannot send request: session was closed"));
>                         return;
>                     }
> 
>                     if (result.isOK()) {
>                         future.complete(null);
>                         return;
>                     }
> 
>                     future.completeExceptionally(result.getException());
>                 });
>             } catch (Throwable throwable) {
>                 future.completeExceptionally(throwable);
>             }
>             return future;
>         }
> 
>         @OnOpen
>         public void onOpen(Session session) {
>             this.session = session;
>             listener.onOpen(this);
>         }
> 
>         @OnClose
>         public void onClose(Session session, CloseReason closeReason) {
>             listener.onClose();
>         }
> 
>         @OnError
>         public void onError(Throwable throwable) {
>             listener.onError(throwable);
>         }
> 
>         @OnMessage
>         public void onBinary(byte[] message) {
>             listener.onMessage(message);
>         }
> 
>         public static class OriginPatcher extends Configurator {
>             @Override
>             public void beforeRequest(@NonNull Map<String, List<String>> headers) {
>                 headers.put("Origin", List.of(Specification.Whatsapp.WEB_ORIGIN));
>                 headers.put("Host", List.of(Specification.Whatsapp.WEB_HOST));
>             }
>         }
>     }
> 
>     public final static class AppSocketSession extends SocketSession {
>         private static final int MAX_READ_SIZE = 65535;
> 
>         private Socket socket;
> -        private ExecutorService service;
> 
> +        public AppSocketSession(ExecutorService executor) {
> +            super(executor);
> +        }
> 
>         @Override
>         public CompletableFuture<Void> connect(SocketListener listener) {
>             if(socket != null && isOpen()){
>                 return CompletableFuture.completedFuture(null);
>             }
> 
>             return CompletableFuture.runAsync(() -> {
>                 try {
>                     super.connect(listener);
>                     this.socket = new Socket();
>                     socket.setKeepAlive(true);
>                     socket.connect(new InetSocketAddress(APP_ENDPOINT_HOST, APP_ENDPOINT_PORT));
> -                    this.service = Executors.newSingleThreadScheduledExecutor();
> U                    executorService.execute(this::readMessages);
>                     listener.onOpen(this);
>                 } catch (IOException exception) {
>                     throw new UncheckedIOException("Cannot connect to host", exception);
>                 }
> U            }, executorService);
>         }
> 
>         @Override
>         public CompletableFuture<Void> close() {
>             if(socket == null || !isOpen()){
>                 return CompletableFuture.completedFuture(null);
>             }
> 
>             return CompletableFuture.runAsync(() -> {
>                 try {
>                     super.close();
>                     socket.close();
>                     closeResources();
>                 } catch (IOException exception) {
>                     throw new UncheckedIOException("Cannot close connection to host", exception);
>                 }
>             });
>         }
> 
>         @Override
>         public boolean isOpen() {
>             return socket.isConnected();
>         }
> 
>         @Override
>         public CompletableFuture<Void> sendBinary(byte[] bytes) {
>             return CompletableFuture.runAsync(() -> {
>                 try {
>                     var stream = socket.getOutputStream();
>                     stream.write(bytes);
>                     stream.flush();
>                 } catch (IOException exception) {
>                     throw new UncheckedIOException("Cannot send message", exception);
>                 }
> U            }, executorService);
>         }
> 
>         private void readMessages() {
>             var bytes = new byte[MAX_READ_SIZE];
>             while (isOpen()) {
>                 try {
>                     var stream = socket.getInputStream();
>                     var size = stream.read(bytes);
>                     listener.onMessage(Arrays.copyOf(bytes, size));
>                 } catch (SocketException exception) {
>                     closeResources();
>                 } catch (IOException exception) {
>                     listener.onError(exception);
>                 }
>             }
>             closeResources();
>         }
> 
>         private void closeResources() {
>             this.socket = null;
>             executorService.shutdownNow();
> -            this.service = null;
>             listener.onClose();
>         }
>     }
> }
> ```
> 
> **SocketHandler.java**
> 
> ```
>     public CompletableFuture<Void> connect() {
>         if (authFuture == null || authFuture.isDone()) {
>             this.authFuture = new CompletableFuture<>();
>         }
> 
>         if(options instanceof MobileOptions mobileOptions && !keys.registered()){
>             authHandler.checkRegistrationStatus();
>         }
> 
> ---    this.session = SocketSession.of(options.clientType());
> +++ this.session = SocketSession.of(options);
>         return session.connect(this).thenCompose(ignored -> authFuture);
>     }
> ```

Can you create a PR? I'll merge it right away

**Comment by stserakhau** [comment]
23:31:02.822: [Whatsapp4j] git -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/Issue-223-executor-customization:refs/heads/Issue-223-executor-customization --set-upstream
remote: Permission to Auties00/Whatsapp4j.git denied to stserakhau.
fatal: unable to access 'https://github.com/Auties00/Whatsapp4j.git/': The requested URL returned error: 403

I havn't permissions

**Comment by Auties00** [comment]
> 23:31:02.822: [Whatsapp4j] git -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/Issue-223-executor-customization:refs/heads/Issue-223-executor-customization --set-upstream remote: Permission to Auties00/Whatsapp4j.git denied to stserakhau. fatal: unable to access 'https://github.com/Auties00/Whatsapp4j.git/': The requested URL returned error: 403
> 
> I havn't permissions

You need to first fork the repo and use that as an upstream. Then create the  PR

**Comment by stserakhau** [comment]
https://github.com/Auties00/Whatsapp4j/pull/230

done

**Comment by Auties00** [comment]
Merged, make sure to specify your executor as I changed your implementation to mirror java's by default

**Comment by stserakhau** [comment]
nice, thanks !
