### ISSUE TITLE
[v3.1.2] No connection, No QR code, Code freezed

### ISSUE THREAD

**Issue by 19Maury85** [Auties00/Whatsapp4j#228]
Hi, I'm try to use the new version (3.1.2) but can't connect.
My code freeze and no QR code shown in console.

I'm using the README code:

`
Whatsapp whatsapp = Whatsapp.lastConnection();
whatsapp.connect().join();

Store store = whatsapp.store();
System.out.println(store.id());
`

**Comment by Auties00** [comment]
> Hi, I'm try to use the new version (3.1.2) but can't connect. My code freeze and no QR code shown in console.
> 
> I'm using the README code:
> 
> ` Whatsapp whatsapp = Whatsapp.lastConnection(); whatsapp.connect().join();
> 
> Store store = whatsapp.store(); System.out.println(store.id()); `

Your code freezes because it's waiting for join to return, which only happens after the connection is closed. For the qr not appearing, you might want to send me your full code so i can check it out

**Comment by Auties00** [comment]
Tracking in #229

**Comment by rward27** [comment]
is anyone able to resolve this issue? I am facing same issue and no QR code is being generated for me either

**Comment by Auties00** [comment]
> is anyone able to resolve this issue? I am facing same issue and no QR code is being generated for me either

Use the latest version

**Comment by rward27** [comment]
Using version 3.2.3

Below is the code I am trying to use:


   ```
 public static void main(String[] args) {
        try {
            WhatsappOptions opt = WhatsappOptions.WebOptions
                    .builder()
                    .autodetectListeners(false)
                    .textPreviewSetting(TextPreviewSetting.ENABLED)
                    .historyLength(HistoryLength.THREE_MONTHS)
                    .errorHandler(ErrorHandler.toTerminal())
                    .qrHandler(QrHandler.toTerminal())
                    .build();

            Whatsapp whatsapp = Whatsapp.newConnection(opt);
            whatsapp.connect().join();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

```

It never prints anything on the console and doesnt even throw any exception ever. Application just keeps running with no output.

Can you please help me resolving the issue?
