### ISSUE TITLE
Issue when sending links on chat

### ISSUE THREAD

**Issue by oPandaTwo** [Auties00/Whatsapp4j#241]
I created a simple bot to get a user handle and return the instagram link associated to this account (Just for testing), but this happens:

code:
```
@Override
    public void onNewMessage(MessageInfo info) {
        AtomicReference<String> atomic = new AtomicReference<>(null);
        info.message().textMessage().ifPresent((txt) -> {
            atomic.set(txt.text());
        });

        String msg = atomic.get();

        if (msg == null || !info.chat().name().equals(ENV.GROUP_NAME) || !msg.contains("@")) {
            return;
        }

        String handle = msg.substring(msg.lastIndexOf('@') + 1).split(" ")[0];
        SWhatsapp.build().app.sendMessage(info.chat(), "https://www.instagram.com/" + handle);
    }
```

but the result on whatssap web is:

![image](https://user-images.githubusercontent.com/50250308/227243946-d7c5776c-cf21-46f5-80d3-845dbe663e44.png)

**Comment by Auties00** [comment]
> I created a simple bot to get a user handle and return the instagram link associated to this account (Just for testing), but this happens:
> 
> code:
> ```
> @Override
>     public void onNewMessage(MessageInfo info) {
>         AtomicReference<String> atomic = new AtomicReference<>(null);
>         info.message().textMessage().ifPresent((txt) -> {
>             atomic.set(txt.text());
>         });
> 
>         String msg = atomic.get();
> 
>         if (msg == null || !info.chat().name().equals(ENV.GROUP_NAME) || !msg.contains("@")) {
>             return;
>         }
> 
>         String handle = msg.substring(msg.lastIndexOf('@') + 1).split(" ")[0];
>         SWhatsapp.build().app.sendMessage(info.chat(), "https://www.instagram.com/" + handle);
>     }
> ```
> 
> but the result on whatssap web is:
> 
> ![image](https://user-images.githubusercontent.com/50250308/227243946-d7c5776c-cf21-46f5-80d3-845dbe663e44.png)
> 

That's happening because of your textPreview setting. Use enabled instead of enabled with inference and that should fix it
