### ISSUE TITLE
QR authorization

### ISSUE THREAD

**Issue by SachukS** [Auties00/Whatsapp4j#253]
In new versions  ability to override QrHandler have removed from code. How i can get it QR to send it to my front for example?

**Comment by SachukS** [comment]
Sorry, just recognized that i can define custom QrHandler through options builder

**Comment by pedroheavy** [comment]
did you find out how to print image and after that call a method?

**Comment by Auties00** [comment]
> did you find out how to print image and after that call a method?

supply a custom qr handler

**Comment by pedroheavy** [comment]
I would like to return my qrcode, but it returns only if I read it.

 api = Whatsapp.webBuilder()
                        .newConnection().name("InterWPP")
                        .unregistered(QrHandler.toFile(temp.toPath(), QrHandler.ToFileConsumer.toTerminal()))
                api.connect().join()

**Comment by Auties00** [comment]
> I would like to return my qrcode, but it returns only if I read it.
> 
>  api = Whatsapp.webBuilder()
>                         .newConnection().name("InterWPP")
>                         .unregistered(QrHandler.toFile(temp.toPath(), QrHandler.ToFileConsumer.toTerminal()))
>                 api.connect().join()

Don't return your qr code, move that login inside a custom qrHandler

**Comment by pedroheavy** [comment]
maybe I'm bad at this, but I really couldn't do anything

**Comment by pedroheavy** [comment]
where can I put a qrHandler? Is it possible in the latest version? I'm using 3.5.1 and the only place I can pass a QrHandler is inside unregistered(), Can you give me a clue or tell what too look into to know how to do it?

**Comment by Auties00** [comment]
> where can I put a qrHandler? Is it possible in the latest version? I'm using 3.5.1 and the only place I can pass a QrHandler is inside unregistered(), Can you give me a clue or tell what too look into to know how to do it?

just pass your custom qr handler there

**Comment by pedroheavy** [comment]
But it executes only after the join(), I want to get the file before the join and after that call another method
