### ISSUE TITLE
Quoted messages are not working properly

### ISSUE THREAD

**Issue by Duckulus** [Auties00/Whatsapp4j#259]
When I invoke messageInfo.quotedMessage() in a newMessage Listener it is always empty, even if the message is a reply to another message.

Another issue is that I cant reply to a message using the sendMessage method. The message just gets sent normally and not as a reply.

Here is a code example:
```kotlin
override fun onNewMessage(info: MessageInfo) {
        if((info.message().content() as TextMessage).text().startsWith(".")) { //preventing infinite reply loop
            println(info.quotedMessage().isEmpty) //I expect it to print false when I reply to a message but it always prints true
            whatsapp.sendMessage(info.chat(), "test", info) //I expect it to reply to my message but it does not
        }
}
```

I am using the newest release 3.2.0

**Comment by Auties00** [comment]
> When I invoke messageInfo.quotedMessage() in a newMessage Listener it is always empty, even if the message is a reply to another message.
> 
> Another issue is that I cant reply to a message using the sendMessage method. The message just gets sent normally and not as a reply.
> 
> Here is a code example:
> 
> ```kotlin
> override fun onNewMessage(info: MessageInfo) {
>         if((info.message().content() as TextMessage).text().startsWith(".")) { //preventing infinite reply loop
>             println(info.quotedMessage().isEmpty) //I expect it to print false when I reply to a message but it always prints true
>             whatsapp.sendMessage(info.chat(), "test", info) //I expect it to reply to my message but it does not
>         }
> }
> ```
> 
> I am using the newest release 3.2.0

Can you try 3.2.3?

**Comment by Duckulus** [comment]
that did not fix it, it behaves the same

**Comment by Duckulus** [comment]
Thank you very much. The first thing I mentioned has been fixed in the new release. The Optional is no longer empty when the messages quotes another one.

But for me it is still not possible to send a message that quotes another. This time when I quote a message the bot doesn't send anything at all.

Here is a minimal code example:
```
api.addNewMessageListener(OnNewMessage { info ->
        api.sendMessage(info.chat(), "A", info) // does nothing
        api.sendMessage(info.chat(), "B") // gets sent
})
```

**Comment by anderson20210704** [comment]
So am I  when I want to reply.  Like do this: 
`api.sendMessage(info.chat(), "A", info) `
but nothing happened.
