### ISSUE TITLE
Session data directory

### ISSUE THREAD

**Issue by NicklasMatzulla** [Auties00/Whatsapp4j#260]
Good day,
I wanted to ask where the session tokens are stored and if I can also implement this as a json file (if I program this myself) with the help of the API.

With kind regards

**Comment by Auties00** [comment]
Implement a custom ControllerSerializer and pass it to the api as an option(see the readme). There is no reason to save data as Json though as it takes up too much space. Currently the session is serialized as a smile file, which is similar to JSON but more efficient, and then compressed using gzip so it takes the least amount of space possible.
