### ISSUE TITLE
Severe socket failure at login

### ISSUE THREAD

**Issue by lollix91** [Auties00/Whatsapp4j#261]
Ciao,
Ho un piccolo problema.
Riesco ad usare la tua libreria senza problemi con la maggior parte degli smartphone con WhatsApp.
Per uno in particolare, però, dopo aver inquadrato il qr code per il login, ottengo il messaggio di errore: Severe socket failure at login.
Il problema accade solamente con quella particolare utenza di whatsapp.
Specifico che WhatsApp sul Device è registrato da parecchio tempo, scrive e riceve normalmente tramite l'app, si collega normalmente a WhatsApp web tramite browser.
Prima della registrazione, elimino i file residui nella cartella WhatsApp4j.
Quale può essere il problema?

**Comment by Auties00** [comment]
> Ciao, Ho un piccolo problema. Riesco ad usare la tua libreria senza problemi con la maggior parte degli smartphone con WhatsApp. Per uno in particolare, però, dopo aver inquadrato il qr code per il login, ottengo il messaggio di errore: Severe socket failure at login. Il problema accade solamente con quella particolare utenza di whatsapp. Specifico che WhatsApp sul Device è registrato da parecchio tempo, scrive e riceve normalmente tramite l'app, si collega normalmente a WhatsApp web tramite browser. Prima della registrazione, elimino i file residui nella cartella WhatsApp4j. Quale può essere il problema?

Hai una stacktrace?

**Comment by Auties00** [comment]
> Ciao, eccoti lo stacktrace:
> 
> `
> java.util.concurrent.CompletionException: java.util.NoSuchElementException: Unknown privacy option: calladd
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Caused by: java.util.NoSuchElementException: Unknown privacy option: calladd
> 	at it.auties.whatsapp.socket.StreamHandler.lambda$addPrivacySetting$24(StreamHandler.java:416)
> 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
> 	at it.auties.whatsapp.socket.StreamHandler.addPrivacySetting(StreamHandler.java:416)
> 	at it.auties.whatsapp.socket.StreamHandler.lambda$parsePrivacySettings$42(StreamHandler.java:633)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
> 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
> 	at it.auties.whatsapp.socket.StreamHandler.parsePrivacySettings(StreamHandler.java:634)
> 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
> 	... 6 more
> `

Si è un bug, lo risolverò appena sarò a casa

**Comment by phegalante** [comment]
I'm going through the same problem.

i can login with my personal number, but when i try to login through whatsapp business, using a virtual number, i get the same error

**Comment by anderson20210704** [comment]
I have also encountered a similar problem where I was able to successfully scan the code on the first attempt, but encountered an error when trying to log in again. However, it seems that the connection should have been successful.

`java.util.concurrent.CompletionException: java.util.NoSuchElementException: Unknown privacy option: calladd
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.NoSuchElementException: Unknown privacy option: calladd
	at it.auties.whatsapp.socket.StreamHandler.lambda$addPrivacySetting$30(StreamHandler.java:443)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.whatsapp.socket.StreamHandler.addPrivacySetting(StreamHandler.java:443)
	at it.auties.whatsapp.socket.StreamHandler.lambda$parsePrivacySettings$48(StreamHandler.java:661)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at it.auties.whatsapp.socket.StreamHandler.parsePrivacySettings(StreamHandler.java:662)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)`

**Comment by Goddino-Repo** [comment]
> > Ciao, eccoti lo stacktrace:
> > `java.util.concurrent.CompletionException: java.util.NoSuchElementException: Unknown privacy option: calladd at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) Caused by: java.util.NoSuchElementException: Unknown privacy option: calladd at it.auties.whatsapp.socket.StreamHandler.lambda$addPrivacySetting$24(StreamHandler.java:416) at java.base/java.util.Optional.orElseThrow(Optional.java:403) at it.auties.whatsapp.socket.StreamHandler.addPrivacySetting(StreamHandler.java:416) at it.auties.whatsapp.socket.StreamHandler.lambda$parsePrivacySettings$42(StreamHandler.java:633) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) at it.auties.whatsapp.socket.StreamHandler.parsePrivacySettings(StreamHandler.java:634) at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ... 6 more`
> 
> Si è un bug, lo risolverò appena sarò a casa

lo dava anche a me fino a qualche minuto fa, ho risolto eliminando la directory .idea e riaprendo il progetto

**Comment by Goddino-Repo** [comment]
update:
Me lo da di nuovo, e sta volta non è servita la risoluzione precedente

**Comment by jefaokpta** [comment]
> I have also encountered a similar problem where I was able to successfully scan the code on the first attempt, but encountered an error when trying to log in again. However, it seems that the connection should have been successful.
> 
> `java.util.concurrent.CompletionException: java.util.NoSuchElementException: Unknown privacy option: calladd at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) Caused by: java.util.NoSuchElementException: Unknown privacy option: calladd at it.auties.whatsapp.socket.StreamHandler.lambda$addPrivacySetting$30(StreamHandler.java:443) at java.base/java.util.Optional.orElseThrow(Optional.java:403) at it.auties.whatsapp.socket.StreamHandler.addPrivacySetting(StreamHandler.java:443) at it.auties.whatsapp.socket.StreamHandler.lambda$parsePrivacySettings$48(StreamHandler.java:661) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) at it.auties.whatsapp.socket.StreamHandler.parsePrivacySettings(StreamHandler.java:662) at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)`

Same problem

**Comment by lucasfmoreno** [comment]
Same problem.

I was using 3.2.3 version and the error is there, but the login didn't crash my app, eventually i updated to the last one because some INITIAL_APP_STATE_SYNC errors happened and those were making it crash.

With the last one (3.3.1 on mvnrepository) the error makes my app to stop, doesn't even login.

**Comment by Goddino-Repo** [comment]
> Same problem.
> 
> I was using 3.2.3 version and the error is there, but the login didn't crash my app, eventually i updated to the last one because some INITIAL_APP_STATE_SYNC errors happened and those were making it crash.
> 
> With the last one (3.3.1 on mvnrepository) the error makes my app to stop, doesn't even login.

I saw the last commit, the problem is fixed, if you clone this repository and you migrate your project into this repo, all should be work, I tested it 😊

**Comment by lucasfmoreno** [comment]
I tried last commit and the "calladd" error is not there anymore, but i'm getting bad mac after scanning. 

`INFO: Saved qr countryCode at qrFile.jpg
abr 29, 2023 1:09:53 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at CRYPTOGRAPHY
java.lang.RuntimeException: Detected a bad mac
	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:528)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:84)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:162)
	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:125)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
abr 29, 2023 1:09:53 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Socket failure at CRYPTOGRAPHY
WARNING: Socket failure at CRYPTOGRAPHY`

I don't know,

**Comment by phegalante** [comment]
> I've tried last commit and the "calladd" error is not there anymore, but i'm getting bad mac after scanning.
> 
> `INFO: Saved qr countryCode at qrFile.jpg abr 29, 2023 1:09:53 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 SEVERE: Socket failure at CRYPTOGRAPHY java.lang.RuntimeException: Detected a bad mac at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:528) at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:84) at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:162) at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:125) at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) abr 29, 2023 1:09:53 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 WARNING: Socket failure at CRYPTOGRAPHY WARNING: Socket failure at CRYPTOGRAPHY`

I still have the same error

**Comment by lollix91** [comment]
Fix temporaneo:
Ho risolto creando un file chiamato StreamHandler.java, con package it.auties.whatsapp.socket.
Poi ho modificato la riga 442, con:

`var privacyType = PrivacySettingType.LAST_SEEN;`
Il problema è che c'è un opzione di privacy sconosciuta "call add" che il software non legge e quinti ritorna errore.
Skippando quella parte di codice, non da più errore e riceve.

**Comment by Auties00** [comment]
> I've tried last commit and the "calladd" error is not there anymore, but i'm getting bad mac after scanning. 
> 
> `INFO: Saved qr countryCode at qrFile.jpg
> abr 29, 2023 1:09:53 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> SEVERE: Socket failure at CRYPTOGRAPHY
> java.lang.RuntimeException: Detected a bad mac
> 	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:528)
> 	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:84)
> 	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:162)
> 	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:125)
> 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> abr 29, 2023 1:09:53 A. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> WARNING: Socket failure at CRYPTOGRAPHY
> WARNING: Socket failure at CRYPTOGRAPHY`

then you haven't tried the latest commit, because the value has been added. I'll push out a new release soon so it's easier

**Comment by Auties00** [comment]
> Fix temporaneo:
> Ho risolto creando un file chiamato StreamHandler.java, con package it.auties.whatsapp.socket.
> Poi ho modificato la riga 442, con:
> 
> `var privacyType = PrivacySettingType.LAST_SEEN;`
> Il problema è che c'è un opzione di privacy sconosciuta "call add" che il software non legge e quinti ritorna errore.
> Skippando quella parte di codice, non da più errore e riceve.
> 

basta usare l'ultimo commit

**Comment by lollix91** [comment]
> > Fix temporaneo:
> > Ho risolto creando un file chiamato StreamHandler.java, con package it.auties.whatsapp.socket.
> > Poi ho modificato la riga 442, con:
> > `var privacyType = PrivacySettingType.LAST_SEEN;`
> > Il problema è che c'è un opzione di privacy sconosciuta "call add" che il software non legge e quinti ritorna errore.
> > Skippando quella parte di codice, non da più errore e riceve.
> 
> basta usare l'ultimo commit

Purtroppo per vari motivi ho dovuto usare il repo su maven, e non ho possibilità di usare l'ultima commit.
Appena uscirà la repo su maven farò l'aggiornamento, Grazie :)

**Comment by niklas-simon** [comment]
> 

I'm just now trying to use the last commit but I get the following error:
/path/to/Whatsapp4j\target\generated-sources\annotations\it\auties\protobuf\ProtobufStubs.java:3:120937
java: incompatible types: invalid method reference
    incompatible types: java.util.Map cannot be converted to java.util.Collection<it.auties.whatsapp.model.chat.GroupParticipant>
where does this come from and how do I fix it?

**Comment by GDB4J** [comment]
> I'll push out a new release soon so it's easier

Hi @Auties00 
Any idea when this new version should be released/available ?
(Current version does not work, as you know)

**Comment by DeepakDhaka201** [comment]
Hi @Auties00 

When are we going to publish the new version with the fix? 

It would be good if you can publish the version a little sooner.

**Comment by DeepakDhaka201** [comment]
> > Same problem.
> > I was using 3.2.3 version and the error is there, but the login didn't crash my app, eventually i updated to the last one because some INITIAL_APP_STATE_SYNC errors happened and those were making it crash.
> > With the last one (3.3.1 on mvnrepository) the error makes my app to stop, doesn't even login.
> 
> I saw the last commit, the problem is fixed, if you clone this repository and you migrate your project into this repo, all should be work, I tested it 😊

Can you share the hash of the commit which is working for you? @Goddino-Repo . I am not sure how to use it.

**Comment by Goddino-Repo** [comment]
@DeepakDhaka201 sincerly I don't remember which commit was
But I suggest you to wait the new release in maven central
New commits have a lot of problems you find in this section of this repository
Some examples:
- exceptions on build
- broken reply on messages
- crash on groups with a lot of participants

**Comment by Auties00** [comment]
The last commit fixes this issue completely, I'll have a release soon enough

**Comment by Auties00** [comment]
The last commit fixes this issue completely, I'll have a release soon enough

**Comment by DeepakDhaka201** [comment]
Thanks @Auties00. We are waiting for the release to publish.

**Comment by Auties00** [comment]
Release 3.4.0 is out @DeepakDhaka201

**Comment by lucasfmoreno** [comment]
With last release still sometimes getting:

`may 19, 2023 6:49:16 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at CRYPTOGRAPHY
java.lang.RuntimeException: Detected a bad mac
	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:547)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:88)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:172)
	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
may 19, 2023 6:49:16 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Socket failure at CRYPTOGRAPHY
may 19, 2023 6:49:17 P. M. it.auties.whatsapp.api.QrHandler$ToFileConsumer lambda$toTerminal$1
INFO: Saved qr code at qrFile.jpg`

with both lastConnection and newConnection.

**Comment by Auties00** [comment]
> With last release still sometimes getting:
> 
> `may 19, 2023 6:49:16 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 SEVERE: Socket failure at CRYPTOGRAPHY java.lang.RuntimeException: Detected a bad mac at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:547) at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:88) at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:172) at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122) at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) may 19, 2023 6:49:16 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 WARNING: Socket failure at CRYPTOGRAPHY may 19, 2023 6:49:17 P. M. it.auties.whatsapp.api.QrHandler$ToFileConsumer lambda$toTerminal$1 INFO: Saved qr code at qrFile.jpg`
> 
> with both lastConnection and newConnection.

Yeah this can sometimes happen in the latest release, I'm trying to fix it

**Comment by lucasfmoreno** [comment]
Maybe the last "solution" if it can't be solved it will be to populate the exception, catch it and try to do stuff.

Don't know what, because it's pretty weird: it's "logged in" (or at least that's what's shown) on cellphone but not on library, so I imagine that disconnecting the library not gonna work.

**Comment by Auties00** [comment]
This issue is fixed
The bad mac is being tracked at https://github.com/Auties00/Whatsapp4j/issues/292
