### ISSUE TITLE
How to terminate connection while registering?

### ISSUE THREAD

**Issue by savox-326** [Auties00/Whatsapp4j#262]
I mean when QR codes send while you not connected to your account how terminate connection

**Comment by Auties00** [comment]
> I mean when QR codes send while you not connected to your account how terminate connection

Use the disconnect method from the api

**Comment by savox-326** [comment]
@Auties00 but if i have this on setup
`whatsapp = Whatsapp.newConnection(createOptions())
                .addLoggedInListener { -> successConnect() }
                .connect()
                .get()`

and run
`whatsapp.disconnect()`
on other thread (for not blocking program) i got something about this "cannot invoke method disconnect() because whatsapp is null"

**Comment by Auties00** [comment]
> @Auties00 but if i have this on setup
> `whatsapp = Whatsapp.newConnection(createOptions())
>                 .addLoggedInListener { -> successConnect() }
>                 .connect()
>                 .get()`
> 
> and run
> `whatsapp.disconnect()`
> on other thread (for not blocking program) i got something about this "cannot invoke method disconnect() because whatsapp is null"

Use the api instance coming from the listener, the instance you are using will be unitialized

**Comment by savox-326** [comment]
What listener should i use 😅
