### ISSUE TITLE
Create a Discord for Whatsapp4j

### ISSUE THREAD

**Issue by Kuroosh** [Auties00/Whatsapp4j#264]
Hello my dear Italian friend :)

I'm new here, since i saw your comment on a baileys repo :)
I will start using ur Mobile-API instantly from now on.
Do you have a Discord-Server for this API?

If no, can you create one? 
i will even help, if necessary i will even moderate it :)

Greets from Germany 
Kuroosh.

**Comment by richard892** [comment]
+1

**Comment by canove** [comment]
https://discord.gg/NkppYGuQ

**Comment by Duckulus** [comment]
> https://discord.gg/NkppYGuQ

that link seems to have expired

**Comment by canove** [comment]
> > https://discord.gg/NkppYGuQ
> 
> that link seems to have expired

updated!

**Comment by Goddino-Repo** [comment]
Where can I get Discord Link? 🤔

**Comment by kellen0903** [comment]
can please share the link again, thanks
