### ISSUE TITLE
can't register

### ISSUE THREAD

**Issue by topskymonk** [Auties00/Whatsapp4j#267]
D:\software\JDK17\bin\java.exe --enable-preview "-javaagent:D:\software\IDEA\IntelliJ IDEA 2022.3.1\lib\idea_rt.jar=65310:D:\software\IDEA\IntelliJ IDEA 2022.3.1\bin" -Dfile.encoding=UTF-8 -classpath D:\code\Whatsapp4j\target\test-classes;D:\code\Whatsapp4j\target\classes;D:\depository\org\projectlombok\lombok\1.18.24\lombok-1.18.24.jar;D:\depository\com\google\zxing\javase\3.5.1\javase-3.5.1.jar;D:\depository\com\google\zxing\core\3.5.1\core-3.5.1.jar;D:\depository\com\beust\jcommander\1.82\jcommander-1.82.jar;D:\depository\com\github\jai-imageio\jai-imageio-core\1.4.0\jai-imageio-core-1.4.0.jar;D:\depository\org\bouncycastle\bcpkix-jdk15on\1.70\bcpkix-jdk15on-1.70.jar;D:\depository\org\bouncycastle\bcutil-jdk15on\1.70\bcutil-jdk15on-1.70.jar;D:\depository\org\bouncycastle\bcprov-jdk15on\1.70\bcprov-jdk15on-1.70.jar;D:\depository\com\github\auties00\protobuf-serializer-performance\1.22\protobuf-serializer-performance-1.22.jar;D:\depository\com\github\auties00\protobuf-base\1.22\protobuf-base-1.22.jar;D:\depository\com\github\auties00\protobuf-serialization-base\1.22\protobuf-serialization-base-1.22.jar;D:\depository\com\fasterxml\jackson\core\jackson-databind\2.14.0\jackson-databind-2.14.0.jar;D:\depository\com\fasterxml\jackson\core\jackson-annotations\2.14.0\jackson-annotations-2.14.0.jar;D:\depository\com\fasterxml\jackson\core\jackson-core\2.14.0\jackson-core-2.14.0.jar;D:\depository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.14.0\jackson-datatype-jsr310-2.14.0.jar;D:\depository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.14.0\jackson-datatype-jdk8-2.14.0.jar;D:\depository\com\fasterxml\jackson\dataformat\jackson-dataformat-smile\2.14.0\jackson-dataformat-smile-2.14.0.jar;D:\depository\com\github\auties00\map-module\1.3\map-module-1.3.jar;D:\depository\com\github\auties00\curve25519\1.1\curve25519-1.1.jar;D:\depository\io\github\classgraph\classgraph\4.8.154\classgraph-4.8.154.jar;D:\depository\com\github\ben-manes\caffeine\caffeine\3.1.2\caffeine-3.1.2.jar;D:\depository\org\checkerframework\checker-qual\3.27.0\checker-qual-3.27.0.jar;D:\depository\com\google\errorprone\error_prone_annotations\2.16\error_prone_annotations-2.16.jar;D:\depository\com\github\auties00\bytes\1.2\bytes-1.2.jar;D:\depository\com\github\auties00\link-preview\2.1\link-preview-2.1.jar;D:\depository\org\jsoup\jsoup\1.15.3\jsoup-1.15.3.jar;D:\depository\com\github\auties00\qr-terminal\2.2\qr-terminal-2.2.jar;D:\depository\com\googlecode\ez-vcard\ez-vcard\0.11.3\ez-vcard-0.11.3.jar;D:\depository\com\github\mangstadt\vinnie\2.0.2\vinnie-2.0.2.jar;D:\depository\org\freemarker\freemarker\2.3.31\freemarker-2.3.31.jar;D:\depository\com\googlecode\libphonenumber\libphonenumber\8.13.7\libphonenumber-8.13.7.jar;D:\depository\org\apache\pdfbox\pdfbox\2.0.27\pdfbox-2.0.27.jar;D:\depository\org\apache\pdfbox\fontbox\2.0.27\fontbox-2.0.27.jar;D:\depository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\depository\org\apache\poi\poi-ooxml\5.2.3\poi-ooxml-5.2.3.jar;D:\depository\org\apache\poi\poi\5.2.3\poi-5.2.3.jar;D:\depository\com\zaxxer\SparseBitSet\1.2\SparseBitSet-1.2.jar;D:\depository\org\apache\poi\poi-ooxml-lite\5.2.3\poi-ooxml-lite-5.2.3.jar;D:\depository\org\apache\xmlbeans\xmlbeans\5.1.1\xmlbeans-5.1.1.jar;D:\depository\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;D:\depository\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;D:\depository\com\github\virtuald\curvesapi\1.07\curvesapi-1.07.jar;D:\depository\org\apache\logging\log4j\log4j-api\2.18.0\log4j-api-2.18.0.jar;D:\depository\org\apache\commons\commons-collections4\4.4\commons-collections4-4.4.jar;D:\depository\org\apache\poi\poi-scratchpad\5.2.3\poi-scratchpad-5.2.3.jar;D:\depository\org\apache\commons\commons-math3\3.6.1\commons-math3-3.6.1.jar;D:\depository\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;D:\depository\org\junit\jupiter\junit-jupiter\5.9.0\junit-jupiter-5.9.0.jar;D:\depository\org\junit\jupiter\junit-jupiter-api\5.9.0\junit-jupiter-api-5.9.0.jar;D:\depository\org\opentest4j\opentest4j\1.2.0\opentest4j-1.2.0.jar;D:\depository\org\junit\platform\junit-platform-commons\1.9.0\junit-platform-commons-1.9.0.jar;D:\depository\org\junit\jupiter\junit-jupiter-params\5.9.0\junit-jupiter-params-5.9.0.jar;D:\depository\org\junit\jupiter\junit-jupiter-engine\5.9.0\junit-jupiter-engine-5.9.0.jar;D:\depository\org\junit\platform\junit-platform-engine\1.9.0\junit-platform-engine-1.9.0.jar;D:\depository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;D:\depository\com\goterl\lazysodium-java\5.1.4\lazysodium-java-5.1.4.jar;D:\depository\com\goterl\resource-loader\2.0.2\resource-loader-2.0.2.jar;D:\depository\org\slf4j\slf4j-api\2.0.3\slf4j-api-2.0.3.jar;D:\depository\net\java\dev\jna\jna\5.12.1\jna-5.12.1.jar;D:\depository\org\bouncycastle\bcmail-jdk15on\1.70\bcmail-jdk15on-1.70.jar;D:\depository\org\bouncycastle\bcpg-jdk15on\1.70\bcpg-jdk15on-1.70.jar it.auties.whatsapp.MyTest
a8poCa7kloj61kd345szVHNLQfE=
WhatsApp/2.23.7.1 Android/13.0 Device/samsung-SM-N950W
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid response, status code 200: {"login":"12364183570","reason":"bad_token","status":"fail"}

	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: Invalid response, status code 200: {"login":"12364183570","reason":"bad_token","status":"fail"}

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at it.auties.whatsapp.util.RegistrationHelper.checkResponse(RegistrationHelper.java:105)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 6 more

**Comment by Auties00** [comment]
read the commit message, I'm working on token generation and it's not working atm

**Comment by topskymonk** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by topskymonk** [comment]
ok，thinks
