### ISSUE TITLE
Detected bad mac (3.3.1 - last commit)

### ISSUE THREAD

**Issue by lucasfmoreno** [Auties00/Whatsapp4j#269]
Getting this error every time i try to connect with newConnection/lastConnection (closing connections on Whatsapp and deleting .whatsapp4j web folder on each new try).

`may 01, 2023 4:29:28 P. M. it.auties.whatsapp.api.QrHandler$ToFileConsumer lambda$toTerminal$1
INFO: Saved qr countryCode at qrFile.jpg
may 01, 2023 4:29:37 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at CRYPTOGRAPHY
java.lang.RuntimeException: Detected a bad mac
	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:529)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:85)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:162)
	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
may 01, 2023 4:29:37 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Socket failure at CRYPTOGRAPHY`

**Comment by Auties00** [comment]
> Getting this error every time i try to connect with newConnection/lastConnection (closing connections on Whatsapp and deleting .whatsapp4j web folder on each new try).
> 
> `may 01, 2023 4:29:28 P. M. it.auties.whatsapp.api.QrHandler$ToFileConsumer lambda$toTerminal$1 INFO: Saved qr countryCode at qrFile.jpg may 01, 2023 4:29:37 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 SEVERE: Socket failure at CRYPTOGRAPHY java.lang.RuntimeException: Detected a bad mac at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:529) at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:85) at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:162) at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122) at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) may 01, 2023 4:29:37 P. M. it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1 WARNING: Socket failure at CRYPTOGRAPHY`

Can you try the latest commit?

**Comment by lucasfmoreno** [comment]
I'm getting 

`[ERROR] /C:/Users/lucas/Downloads/Whatsapp4j/target/generated-sources/annotations/it/auties/protobuf/ProtobufStubs.java:[3,269162] incompatible types: invalid method reference
[ERROR]     incompatible types: java.util.Map cannot be converted to java.util.Collection<it.auties.whatsapp.model.chat.GroupParticipant>
`

When i do a clean install on the last commit (skipping tests).

**Comment by Auties00** [comment]
Tracking in https://github.com/Auties00/Whatsapp4j/issues/261
