### ISSUE TITLE
handling incoming voice calls on WhatsApp programmatically

### ISSUE THREAD

**Issue by badereddineqodia** [Auties00/Whatsapp4j#272]
I am interested in handling incoming voice calls on WhatsApp programmatically.

Receive incoming WhatsApp calls
Answer the call
Receive streaming data and send data back simultaneously in a bidirectional connection
End the call

**Comment by Auties00** [comment]
Sorry that's not possible currently

**Comment by brewkon** [comment]
https://github.com/brewkon/Whatsapp-Call
This project implements voice calls
