### ISSUE TITLE
Can not reply to messages

### ISSUE THREAD

**Issue by Duckulus** [Auties00/Whatsapp4j#275]
Hey, it is not possible for me to reply to messages. When I try to, no message gets sent at all.
I am using version 3.3.1
Code example:
```kotlin
api.addNewMessageListener(OnNewMessage { info ->
        api.sendMessage(info.chat(), "A", info) // does nothing
        api.sendMessage(info.chat(), "B") // gets sent normally
})
```

**Comment by Auties00** [comment]
Okay this is 100% a bug, i'll fix it

**Comment by Auties00** [comment]
This issue is now fixed on the master branch
