### ISSUE TITLE
Trying to Restore Session but got Error 401 Unpaired with Cellphone

### ISSUE THREAD

**Issue by xianliu18** [Auties00/Whatsapp4j#277]
First, I scan QR Code, and generate **keys.json** and **session.json**. I change ***.smile** back to ***.json**.
Second, I restart my application, and try to restore session using already generated *.json file, got 401 Error.

When I use old version, I can use generated *.json. 

After the code is updated, is there an error in the parameters I requested?

**Comment by Auties00** [comment]
the library serializes its data as a gzip encoded smile file. It's not a JSON, and it's not even a decoded file. I have no idea what you are referring to
