### ISSUE TITLE
incorrect latitude, longitude info

### ISSUE THREAD

**Issue by ksproyectos** [Auties00/Whatsapp4j#283]
incorrect latitude/longitude info when get a new location message

**Comment by Auties00** [comment]
what version are you using?

**Comment by ksproyectos** [comment]
> what version are you using?

master branch.

**Comment by Auties00** [comment]
can you try now?
also can you show me the actual value vs the expected one?

**Comment by Auties00** [comment]
Fixed on the master branch, this was indeed a bug
