### ISSUE TITLE
Unable to get stuff from the store

### ISSUE THREAD

**Issue by open-sudo** [Auties00/Whatsapp4j#295]
I star messages in whatsapp and I am not able to find them in the store. The way I do is this:
```
whatsapp.store().starredMessages().size()
```
No matter how many messages I star, this keeps giving me 0.
I also tried to get messages that are reacted upon. I received the ReactionMessage but I am not able to find the message that the used is interacted on. Here is my code:

```
                   MessageKey key=((ReactionMessage)info.message().content()).key();
                    Optional<MessageInfo> message=whatsapp.store().findMessageByKey(key);
                    if(message.isPresent()){
                        System.out.println("Reacted message:"+message.get().toJson());
                    }else{
                        System.out.println("No reacted message:");
                    }
```

No matter what I do, I get "No reacted message". Please help.

**Comment by open-sudo** [comment]
It looks like starring a message is a local feature in whatsapp. User A does not normally sees the stars made by user B. So first item is a non-issue.

The issue that is still a challenge to me is how to find out what message was reacted upon. When I get a ReactionMessage, it only includes the reaction (like thumps up, Plus sign). I am not able to find what message the reaction is placed on.

**Comment by Auties00** [comment]
Tracking in https://github.com/Auties00/Whatsapp4j/issues/303
