### ISSUE TITLE
UnsupportedOperationException while calling the "queryGroupMetadata" method

### ISSUE THREAD

**Issue by tomlux** [Auties00/Whatsapp4j#296]
Hy,
I have problems with using the "queryGroupMetadata" method.
I have tested it against the latest git version.

While running this:
>         Set<Chat> groups = api.store().findChatsByName("xxyyzz");
>         Chat group = groups.stream().findFirst().get()
>         System.out.println("group.isGroup = " + group.isGroup());
>         System.out.println("group.name = " + group.name());
>         GroupMetadata groupMetadata = api.queryGroupMetadata(group.toJid()).join();
>         System.out.println("groupMetadata = " + groupMetadata);

I'm getting an "UnsupportedOperationException" exception:

> group.isGroup = true
> group.name = xxyyzz
> Exception in thread "main" java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Caused by: java.lang.UnsupportedOperationException
> 	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.addAll(ConcurrentHashMap.java:4747)
> 	at it.auties.whatsapp.socket.SocketHandler.handleGroupMetadata(SocketHandler.java:484)
> 	at it.auties.whatsapp.socket.SocketHandler.lambda$queryGroupMetadata$19(SocketHandler.java:472)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
> 	... 6 more

**Comment by Auties00** [comment]
should be already fixed on matter

**Comment by tomlux** [comment]
it's working. Thanks 👍

**Comment by GDB4J** [comment]
@Auties00 
Any ETA when this fix should available on next version?

**Comment by Auties00** [comment]
> @Auties00 Any ETA when this fix should available on next version?

might take a while because I'm working on a lot of features

**Comment by GDB4J** [comment]
Problem seems fixed in version 3.4.4

Thanks!

@Auties00 
This issue can be closed i think
