### ISSUE TITLE
How to remove a reaction

### ISSUE THREAD

**Issue by open-sudo** [Auties00/Whatsapp4j#299]
I see there is a method Whatsapp.removeReaction(). But I am not able to find out how to create the MessageInfo that it requires.  I also tried to modify a reaction that the user previously sent by removing its content and reposting it back into the chat. Like this:

```
  ((ReactionMessage)info.message().content()).content(null);
  whatsapp.removeReaction(reacted);
```
This did not help either. Thoughts?

**Comment by Auties00** [comment]
> hod Whatsapp.removeReaction(). But I am not able to find out how to create the MessageInfo that it requires

You can't create that message info, you need to query it from the store
