### ISSUE TITLE
How learn what's type of HistorySyncMessage?

### ISSUE THREAD

**Issue by savox-326** [Auties00/Whatsapp4j#301]
At 3.2.3 version I just used cast message to ImageMessage, TextMessage and so on. But now I don't know how learn what is type of message pulled from chat because media messages doesn't implements or extends MessageInfo

**Comment by Auties00** [comment]
> At 3.2.3 version I just used cast message to ImageMessage, TextMessage and so on. But now I don't know how learn what is type of message pulled from chat because media messages doesn't implements or extends MessageInfo

You can just access the inner messageInfo by using .message()

**Comment by savox-326** [comment]
@Auties00 I did that, and what to do farther? I got MessageInfo but that still isn't use for VideoMessage, StickerMessage... I just want handle message type, it is essential for me. Thanks

**Comment by Auties00** [comment]
> @Auties00 I did that, and what to do farther? I got MessageInfo but that still isn't use for VideoMessage, StickerMessage... I just want handle message type, it is essential for me, I didn't find methods for that (after .message() ). Thanks

Let's say you have a history sync message:
historySyncMessage.message().message(().content()
And you'll have the message
